services:
  crosstool-ng-builder:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      target: crosstoolng
      cache_from:
        - uilianries/crosstoolng-builder:latest
      args:
        CROSSTOOLNG_VERSION: 1.27.0
    image: uilianries/crosstoolng-builder:latest
    container_name: crosstoolng-builder
    tty: true

  crosstool-ng-conan:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      target: conan
      cache_from:
        - uilianries/crosstoolng-conan:latest
      args:
        CONAN_VERSION: 2.17.0
        CMAKE_VERSION: 3.31.8
    image: uilianries/gcc13-crosstoolng:latest
    container_name: crosstoolng-conan-gcc13
    tty: true