name: Build Docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    name: Build GCC-13 Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Setup Compose
        uses: docker/setup-compose-action@v1.2.0

      - name: Pull Docker images as cache
        run: |
          docker compose pull -q crosstool-ng-builder
          docker compose pull -q crosstool-ng-conan

      - name: Build Docker image
        run: |
          docker compose build --pull crosstool-ng-builder
          docker compose build --pull crosstool-ng-conan

      - name: Collect GCC dumpspecs
        run: docker compose run --rm crosstool-ng-conan /opt/x-tools/x86_64-linux-gnu/bin/x86_64-linux-gnu-gcc -dumpspecs > gcc-dumpspecs.txt

      - name: Store GCC dumpspecs
        uses: actions/upload-artifact@v4
        with:
          name: gcc-dumpspecs
          path: gcc-dumpspecs.txt

      - name: Push Docker images
        run: docker compose push

      - name: Validate GCC and Conan
        run: |
          docker compose run --rm crosstool-ng-conan /opt/x-tools/x86_64-linux-gnu/bin/x86_64-linux-gnu-gcc --version
          docker compose run --rm crosstool-ng-conan /opt/x-tools/x86_64-linux-gnu/bin/x86_64-linux-gnu-g++ --version
          docker compose run --rm crosstool-ng-conan conan --version

      - name: Build zlib using Conan
        run: docker compose run --rm crosstool-ng-conan conan install -r conancenter --requires=zlib/1.3.1 -o "*/*:shared=False" --build=missing

      - name: Build wayland using Conan
        run: docker compose run --rm crosstool-ng-conan conan install -r conancenter --requires=wayland/1.23.0 -o "*/*:shared=True" --build=missing

      - name: Build Boost using Conan
        run: docker compose run --rm crosstool-ng-conan conan install -r conancenter --requires=boost/1.88.0 -o "*/*:shared=False" --build=missing

      - name: Build Protobuf using Conan
        run: docker compose run --rm crosstool-ng-conan conan install -r conancenter --requires=protobuf/6.30.1 -o "*/*:shared=False" --build=missing
