name: Build Docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    name: Build GCC-13 Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Setup Compose
        uses: docker/setup-compose-action@v1.2.0

      - name: Build Docker image
        run: docker compose build

      - name: Collect GCC dumpspecs
        run: docker compose run --rm crosstool-ng-conan /opt/x-tools/x86_64-linux-gnu/bin/x86_64-linux-gnu-gcc -dumpspecs > gcc-dumpspecs.txt

      - name: Store GCC dumpspecs
        uses: actions/upload-artifact@v4
        with:
          name: gcc-dumpspecs
          path: gcc-dumpspecs.txt

      - name: Push Docker images
        run: docker compose push
