name: Build Docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    name: Build GCC-13 Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Setup Compose
        uses: docker/setup-compose-action@v1.2.0

      - name: Build Docker image
        run: docker-compose build
